name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask import test
      run: |
        python -c "import flask; print('Flask imported successfully')"

  # Optional: Build Docker image (for testing)
  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t feedback-app .

    # Optional: Log in to Docker Hub and push image (Add secrets DOCKERHUB_USERNAME, DOCKERHUB_TOKEN in repo settings)
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Push Docker image
    #   run: |
    #     docker tag feedback-app ${{ secrets.DOCKERHUB_USERNAME }}/feedback-app:latest
    #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/feedback-app:latest
